[package]
name = "notan_touchy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
notan_core = "0.9.3"
notan_log = "0.9.3"


[dev-dependencies]
